"use client";
import Head from "next/head";
import { Container, Text, Center } from "@mantine/core";

interface PageProps {
  children: React.ReactNode;
}

// interface CenterStyle {
//   background?: string;
//   padding?: string;
//   position?: string;
//   top?: string;
//   left?: string;
//   right?: string;
//   zIndex?: string;
// }

function Page({ children }: PageProps) {
  return (
    <html lang="en">
      <Head>
        <title>Grasia Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <main>
          <Container mt={64}>{children}</Container>
        </main>
      </body>
    </html>
  );
}

export default Page;
