"use client";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Box, Title, Text, Center, Button } from "@mantine/core";
import Navbar from "./_components/Navbar";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Grasia Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Center sx={{ padding: "6rem 0" }}>
          <Box>
            <Title align={"center"} order={1} mb={8}>
              <Text color={"violet"} inherit component={"span"}>
                Build{" "}
              </Text>{" "}
              and{" "}
              <Text color={"violet"} inherit component={"span"}>
                optimize{" "}
              </Text>{" "}
              your resume
            </Title>
            <Text align={"center"} mb={32}>
              Completely free to use, create and download Clean ATS-friendly
              resume format to ensure you get seen by recruiters
            </Text>
            <Box
              style={{
                position: "relative",
                height: "60vh",
                width: "100%",
                boxShadow: "rgba(0, 0, 0, 0.15) 0px 5px 5px",
              }}
            >
              <Image
                src="/hero.webp"
                alt={"hero"}
                layout={"fill"}
                objectFit={"contain"}
                priority
              />
            </Box>
            <Center mt={16}>
              <Link href="/resumeBuilder/createResume" passHref>
                <Button component="a" color={"violet"} variant={"outline"}>
                  Create Resume
                </Button>
              </Link>
            </Center>
          </Box>
        </Center>
      </main>
    </Box>
  );
};

export default Home;
