"use client";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Box, Title, Text, Center, Button } from "@mantine/core";
import Navbar from "./_components/Navbar";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Grasia Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Center sx={{ padding: "6rem 0" }}>
          <Box>
            <Title align={"center"} order={1} mb={8}>
              <Text color={"#228BE6"} component={"span"}>
                Build{" "}
              </Text>{" "}
              and{" "}
              <Text color={"#228BE6"} inherit component={"span"}>
                optimize{" "}
              </Text>{" "}
              your Resume
            </Title>
            <Text align={"center"} mb={32}>
              Completely free to use, create and download Clean ATS-friendly
              resume format to ensure you get seen by recruiters
            </Text>
            <Box
              style={{
                position: "relative",
                // height: "60vh",
                width: "100%",
                // boxShadow: "rgba(0, 0, 0, 0.15) 0px 5px 5px",
              }}
            >
              <Image
                src="/resumeBuilder.png"
                alt={"resumeBuilder"}
                // layout={"fill"}
                // objectFit={"contain"}
                height={1000}
                width={1000}
                priority
              />
            </Box>
            <Center mt={26}>
              <Link href="/resumeBuilder/createResume" passHref>
                <button
                  color="#228BE6"
                  className="flex spa justify-center rounded-md bg-blue-500 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-500"
                >
                  Create Resume
                </button>
              </Link>
            </Center>
          </Box>
        </Center>
      </main>
    </Box>
  );
};

export default Home;
