// import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import Navbars from "./jobportal/homepage/Navbars";
// import Footer from "./components/footer/Footer";
// import SearchForm from "./jobportal/homepage/SearchForm";
// import JobsByCategory from "./jobportal/homepage/JobsByCategory";
// import Tester from "./jobportal/homepage/Tester";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const SampleComponent: React.FC = () => {
//   const dummyJobs = [
//     {
//       id: 1,
//       company: "Sample Company 1",
//       title: "Job Title 1",
//       image: "/glogo.png",
//     },
//     {
//       id: 2,
//       company: "Sample Company 2",
//       title: "Job Title 2",
//       image: "/glogo.png",
//     },
//     {
//       id: 3,
//       company: "Sample Company 3",
//       title: "Job Title 3",
//       image: "/glogo.png",
//     },

//     // Add more jobs as needed
//   ];

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbars />
//         {children}
//         <SearchForm />
//         <div className="flex justify-end ">
//           <AdSection />
//         </div>
//         <div className="mt-5">
//           <JobsByCategory category="Sample Category" jobs={dummyJobs} />
//           <JobsByCategory category="Sample Category" jobs={dummyJobs} />
//         </div>
//         <Footer />
//       </body>
//     </html>
//   );
// };

// export default SampleComponent;

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbars from "./jobportal/homepage/Navbars";
import Footer from "./components/footer/Footer";
// import About from "./about/page";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Gresia Job Portal",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <About /> */}

        <Navbars />

        {children}
        {/* <Tester /> */}
        <Footer />
      </body>
    </html>
  );
}
